spring:
  application:
    name: "config-server"
  profiles:
     active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aceviper404/bank-configuration.git
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

#       native:
#       search-locations: "classpath:/config"


server:
  port: 8888
